### ISSUE TITLE
Not requiring the correct version of express

### ISSUE THREAD

**Issue by heavysixer** [filearts/plunker#18]
I believe that you are requiring a version of express 2.5.x that doesn't support the syntax used inside your index.coffee file:

module.exports = app = express()

When I fire it up I get object is not a function. However, when I update to 3.x version of express the server "almost" starts but fails further down on other dependencies.
